name: pytest

on:
  pull_request:
    branches:    
      - master
      - dev
  workflow_dispatch:

jobs:
  pytests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      PYTHONPATH: ${{ github.workspace }}
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install proj-bin on Ubuntu
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt-get install proj-bin

      - name: Install proj on macOS
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew install proj

      - name: run the tests
        run: pytest tests/

